name: Build Hugo and Publish on Netlify

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
# masterブランチをチェックアウト
      - uses: actions/checkout@v2
      - name: Build Hugo
        run: docker-compose up

      # netlify-cli使ってデプロイ
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      run: npx netlify-cli deploy --dir=./dist --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} 
      # - name: Publish
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --dir=./docs --prod
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}