name: Build Hugo and Publish on Netlify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# masterブランチをチェックアウト
      - uses: actions/checkout@v2
      - name: Build Hugo
        run: docker-compose up
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}