name: Build Hugo and Publish on Netlify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# masterブランチをチェックアウト
      - uses: actions/checkout@v2
      - name: Build Hugo
        run: docker-compose up
      - name: Check files
        run: |
          cd docs
          ls -a
      - name: Commit files
        run: |
          git config --local user.email "okms310gmail.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "Generate By Github Action"

      
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Publish
  #       uses: netlify/actions/cli@master
  #       with:
  #         args: deploy --dir=docs --prod
  #       env:
  #         # NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}