name: Build Hugo and Publish on Netlify

on: 
  workflow_dispatch:
    inputs:
      comment:
        description: "コメント"
        required: false
        default: "手動ビルド"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # masterブランチをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          submodules: true
      - name: Build Hugo
        run: docker-compose up

      # netlify-cli使ってデプロイ
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npx netlify-cli deploy --dir=docs --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} 