name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
# masterブランチをチェックアウト
    - uses: actions/checkout@v2
    - name: Build Hugo
      run: docker-compose up
    - name: Commit files
      run: |
        ls
        git config --local user.email "okms310gmail.com"
        git config --local user.name "Github Action"
        git add .
        git commit -m "Generate By Github Action"
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}