name: Deploy Netlify2

on: 
  workflow_dispatch:
    inputs:
      comment:
        description: "コメント"
        required: false
        default: "手動ビルド"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # masterブランチをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          submodules: true
      - name: Build Hugo
        run: docker-compose up

      # netlify-cli使ってデプロイ
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npx netlify-cli deploy --dir=docs --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} > res
      # 通知
      - name: notify success to slack
        run: grep "URL:" res | echo {\"text\":\"Successful deploy on Netlify\\n`cat`\"} | curl -d @- ${{ secrets.SLACK_WEBHOOK_URL }}

