name: Build Hugo and Publish on Netlify

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
# masterブランチをチェックアウト
      - uses: actions/checkout@v2
      - name: Build Hugo
        run: docker-compose up
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}