name: Shoe Properties yuki

on:
    workflow_dispatch:
        inputs:
            comment:
                description: "コメント"
                required: false
                default: "手動ビルド"

jobs:
    show-properties:
        runs-on: ubuntu-latest
        steps:
            - name: Show github Properties
              run: |
                echo ${{ github.workflow }}
                echo ${{ github.ref }}
                echo ${{ github.sha }}
            - name: Show secret Properties
              run: |
                echo ${{ secrets.SAMPLE }}
            - name: Show inputs Properties
              run: |
                echo ${{ github.event.inputs.comment }}